version: '3'

env:
  GITHUB_USER: merusso

dotenv:
  - .env
  - .ignore/.env

tasks:
  bootstrap: 
    desc: Bootstrap Flux on a new cluster
    # cmd: flux bootstrap github
    #   --owner={{.GITHUB_USER}}
    #   --repository=fleet-infra
    #   --branch=main
    #   --path=./clusters/my-cluster
    #   --personal
    cmds:
      - task: install
      - task: bootstrap-git-secret
      - kubectl apply -f clusters/my-cluster/flux-system
  
  bootstrap-git-secret:
    cmd: >
      flux create secret git flux-system --username $GITHUB_USER --password $GITHUB_TOKEN
      --url=https://github.com/merusso/fleet-infra.git

  install: flux install
  
  reconcile:
    desc: Manually trigger Flux reconciliation
    cmds:
      - flux reconcile kustomization flux-system --with-source
      - flux reconcile source git cluster-components
      - flux reconcile kustomization components --with-source

  suspend: flux suspend kustomization flux-system
  resume: flux resume kustomization flux-system
  
  uninstall:
    desc: Uninstall Flux on a cluster
    summary: |
      Uninstall Flux on a cluster.
      Note: Does not remove components installed via Flux
    cmd: flux uninstall
