---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: components
  namespace: flux-system
spec:
  chart:
    spec:
      chart: camel/components
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
  interval: 10m0s
