---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cluster-components-flux
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/merusso/cluster-components-flux.git
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: components
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/merusso/clusters-flux.git
  include:
    - repository:
        name: cluster-components-flux
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: components
  namespace: flux-system
spec:
  interval: 10m0s
  path: alpaca/components/
  prune: true
  sourceRef:
    kind: GitRepository
    name: components
  dependsOn:
    - name: flux-system