apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../cluster-components-flux
- ../../cluster-components-flux/optional/charlie.yaml

labels:
  - pairs:
      gwcp.guidewire.com/dept: '2'
      atmos-cluster: badger
